# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/@azure-tools
    - sdk/@azure-tools/ci.yml
    - sdk/@azure-tools/Azure.Compute.Batch

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/@azure-tools
    - sdk/@azure-tools/ci.yml
    - sdk/@azure-tools/Azure.Compute.Batch

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: @azure-tools
    ArtifactName: packages
    Artifacts:
    - name: Azure.Compute.Batch
      safeName: AzureComputeBatch
